Repository stride3d/stride-docs, pull requests merged in 2024-02, with the labels that each got.

#240 feat: Release notes content improvements
  en/ReleaseNotes/ReleaseNotes.md
Labels: content

#242 feat: Bullet points styling updated
  en/ReleaseNotes/ReleaseNotes.md
Labels: content

#245 [Contributors] - Content improvements
  en/ReleaseNotes/ReleaseNotesNext.md
  en/contributors/contribution-workflow.md
  en/contributors/documentation/major-release-workflow.md
  en/contributors/engine/building-source-windows.md
  en/contributors/major-release-workflow.md
  en/contributors/toc.yml
  en/contributors/website/major-release-workflow.md
  en/docfx.json
  en/manual/requirements/index.md
Labels: content

#247 chore: GitHub Action dependencies bumped to v4
  .github/workflows/stride-docs-github.yml
  .github/workflows/stride-docs-release-azure.yml
  .github/workflows/stride-docs-release-fast-track-azure.yml
  .github/workflows/stride-docs-staging-azure.yml
  .github/workflows/stride-docs-staging-fast-track-azure.yml
  .github/workflows/stride-docs-wiki.yml
Labels: ci-cd

#248 feat: Content improvements
  README.md
  en/docfx.json
  wiki/Content.md
  wiki/Deployment-Azure.md
  wiki/Deployment.md
  wiki/DocFX.md
  wiki/Home.md
  wiki/Installation.md
  wiki/Roadmap.md
  wiki/Troubleshooting-and-FAQ.md
  wiki/Understanding-the-Stride-Documentation-Generation-Pipeline.md
  wiki/_Sidebar.md
Labels: content

#250 Update install stride page
  en/manual/get-started/install-stride.md
  en/manual/get-started/launch-stride.md
  en/manual/get-started/media/install-VS-plug-in-prompt.png
  en/manual/get-started/media/install-VS-plug-in-prompt.webp
  en/manual/get-started/media/install-dotnet-SDK.webp
  en/manual/get-started/media/install-stride-create-application-shortcuts.png
  en/manual/get-started/media/install-stride-create-application-shortcuts.webp
  en/manual/get-started/media/install-stride-installation-status.png
  en/manual/get-started/media/install-stride-installation-status.webp
  en/manual/get-started/media/install-stride-installation-type.png
  en/manual/get-started/media/install-stride-installation-type.webp
  en/manual/get-started/media/install-stride-license-agreement.png
  en/manual/get-started/media/install-stride-ready-to-install.png
  en/manual/get-started/media/install-stride-ready-to-install.webp
  en/manual/get-started/media/install-stride-select-installation-folder.png
  en/manual/get-started/media/install-stride-select-installation-folder.webp
  en/manual/get-started/media/install-stride-setup-wizard.png
  en/manual/get-started/media/install-stride-setup-wizard.webp
  en/manual/get-started/media/installing-vs-build-tools.png
  en/manual/get-started/media/prerequisites-installer.png
  en/manual/get-started/media/prerequsites-installer2.png
  en/manual/get-started/media/stride-launcher-install-last-version.png
  en/manual/get-started/media/stride-launcher-install-latest-version-prompt.webp
  en/manual/get-started/media/stride-launcher-install-latest-version.webp
  en/manual/get-started/media/stride-launcher-ready.webp
  en/manual/get-started/media/stride-launcher.png
  en/manual/get-started/media/stride-launcher.webp
  en/manual/get-started/media/stride-privacy-policy-prompt.webp
  en/manual/get-started/visual-studio-extension.md
  en/manual/stride-launcher/index.md
Labels: content, manual

#252 Update stride doesn't run troubleshooting page
  en/manual/get-started/media/installing-vs-build-tools-dark.webp
  en/manual/get-started/media/installing-vs-build-tools.webp
  en/manual/troubleshooting/media/programs-and-features-redistributable.png
  en/manual/troubleshooting/media/programs-and-features-redistributable.webp
  en/manual/troubleshooting/media/programs-and-features.png
  en/manual/troubleshooting/stride-doesnt-run.md
Labels: content, manual

#257 fix: Links and references corrected
  Stride.Docs.csproj
  en/community-resources/coding.md
  en/community-resources/embedded-stride.md
  en/community-resources/engine.md
  en/community-resources/example-projects.md
  en/community-resources/games-and-demos.md
  en/community-resources/models-and-animations.md
  en/community-resources/physics.md
  en/community-resources/rendering-and-camera.md
  en/community-resources/shaders.md
  en/community-resources/toc.yml
  en/community-resources/tutorials-and-articles.md
  en/community-resources/ui.md
  en/manual/physics/raycasting.md
Labels: content
