Repository stride3d/stride-docs, pull requests merged in 2024-09, with the labels that each got.

#316 docs: Clarify AsyncScript usage
  en/manual/scripts/types-of-script.md
Labels: content, manual

#317 fix: Remove duplicate rows
  en/manual/graphics/materials/shading-attributes.md
Labels: manual

#318 Update 24 - Readability improvements
  en/manual/graphics/materials/shading-attributes.md
  en/manual/index.md
  en/manual/scripts/types-of-script.md
Labels: manual

#319 Initiating deployment of latest docs updates to staging
  en/manual/graphics/materials/shading-attributes.md
  en/manual/index.md
  en/manual/scripts/types-of-script.md
Labels: deployment

#323 Update 25 - Add core team
  en/contributors/core-team.md
  en/contributors/index.md
  en/contributors/roadmap.md
  en/contributors/toc.yml
Labels: contributing

#325 Initiating deployment of latest docs updates to staging
  en/contributors/core-team.md
  en/contributors/index.md
  en/contributors/roadmap.md
  en/contributors/toc.yml
  en/manual/graphics/textures/index.md
  en/manual/graphics/textures/skyboxes-and-backgrounds.md
  jp/manual/graphics/textures/skyboxes-and-backgrounds.md
Labels: deployment

#328 Initiating deployment of latest docs updates to production
  .github/release.yml
  .github/workflows/stride-docs-github.yml
  .github/workflows/stride-docs-release-azure.yml
  .github/workflows/stride-docs-release-fast-track-azure.yml
  .github/workflows/stride-docs-staging-azure.yml
  .github/workflows/stride-docs-staging-fast-track-azure.yml
  BuildDocs.ps1
  en/community-resources/physics.md
  en/contributors/core-team.md
  en/contributors/engine/architecture/build-details.md
  en/contributors/index.md
  en/contributors/roadmap.md
  en/contributors/toc.yml
  en/diagnostics/STRDIAG010.md
  en/examples/Stride.Utilities-examples.md
  en/examples/Stride.Utilities-remarks.md
  en/manual/audio/custom-audio-data.md
  en/manual/engine/entity-component-system/flexible-processing.md
  en/manual/engine/file-system.md
  en/manual/files-and-folders/distribute-a-game.md
  en/manual/game-studio/index.md
  en/manual/get-started/launch-stride.md
  en/manual/get-started/visual-studio-extension.md
  en/manual/graphics/materials/shading-attributes.md
  en/manual/graphics/textures/index.md
  en/manual/graphics/textures/skyboxes-and-backgrounds.md
  en/manual/index.md
  en/manual/nuget/create-packages.md
  en/manual/physics/fix-physics-jitter.md
  en/manual/platforms/index.md
  en/manual/platforms/linux/setup-and-requirements.md
  en/manual/requirements/index.md
  en/manual/scripts/gizmos.md
  en/manual/scripts/index.md
  en/manual/scripts/media/gizmo.png
  en/manual/scripts/types-of-script.md
  en/manual/toc.yml
  en/manual/troubleshooting/stride-doesnt-run.md
  en/toc.yml
  en/tutorials/toc.yml
  jp/manual/files-and-folders/distribute-a-game.md
  jp/manual/graphics/textures/skyboxes-and-backgrounds.md
  jp/manual/requirements/index.md
Labels: deployment

#329 Update core-team.md
  en/contributors/core-team.md
Labels: contributing

#330 Update 24 - Content improvements and updates
  README.md
  en/community-resources/coding.md
  en/community-resources/embedded-stride.md
  en/community-resources/games-and-demos.md
  en/community-resources/index.md
  en/community-resources/toc.yml
  en/community-resources/tutorials-and-articles.md
  en/contributors/engine/building-source-windows.md
  en/contributors/index.md
  en/contributors/toc.yml
Labels: contributing

#331 Initiating deployment of latest docs updates to staging
  README.md
  en/community-resources/coding.md
  en/community-resources/embedded-stride.md
  en/community-resources/games-and-demos.md
  en/community-resources/index.md
  en/community-resources/toc.yml
  en/community-resources/tutorials-and-articles.md
  en/contributors/core-team.md
  en/contributors/engine/building-source-windows.md
  en/contributors/index.md
  en/contributors/toc.yml
  en/manual/index.md
Labels: deployment

#332 docs: Documentation update to improve user guidance and installation instructions.
  en/manual/get-started/index.md
  en/manual/get-started/install-stride.md
Labels: manual

#333 Initiating deployment of latest docs updates to staging
  LICENSE.md
  en/manual/get-started/index.md
  en/manual/get-started/install-stride.md
Labels: deployment

#334 fix: Link corrected
  en/manual/get-started/index.md
Labels: manual

#335 Initiating deployment of latest docs updates to production
  LICENSE.md
  README.md
  en/community-resources/coding.md
  en/community-resources/embedded-stride.md
  en/community-resources/games-and-demos.md
  en/community-resources/index.md
  en/community-resources/toc.yml
  en/community-resources/tutorials-and-articles.md
  en/contributors/core-team.md
  en/contributors/engine/building-source-windows.md
  en/contributors/index.md
  en/contributors/toc.yml
  en/manual/get-started/index.md
  en/manual/get-started/install-stride.md
Labels: deployment
